# Use CLI as below
# ansible-playbook dict_example.yml --extra-var "ip=172.19.0.3 comp=backend"
- name:  Argument Variable based attribute extraction from a dictionary
  hosts: localhost

  vars:
    components:
      frontend:
        ip: 172.19.0.1
        path: /etc/lib/
      backend:
        ip: 172.19.0.2
        path: /usr/bin/
      database:
        ip: 172.19.0.3
        path: /java/usr/bin
        
  tasks:
    # with predefined vars
    - name: Option1
      debug:
        msg: "User {{ item.key }} is {{ item.value.ip }} ({{ item.value.path }})"
      loop: "{{ lookup('ansible.builtin.dict', components) }}"
      #when: "'172.19.0.3' in item.value.ip"
      when: "'{{ ip }}' in item.value.ip"
    # Items from loop can be used in when: statements
    - name: set_fact when backend in key
      ansible.builtin.set_fact:
        ip_exists: true
      loop: "{{ lookup('ansible.builtin.dict', components) }}"
      when: "'backend' in item.key"
    - name: set_fact when ip in key
      ansible.builtin.set_fact:
        ip_exists: true
      loop: "{{ lookup('ansible.builtin.dict', components) }}"
      when: "'{{ ip }}' in item.value.ip"
